name: run_to_canada
description: Transform your daily runs into virtual journeys to anywhere in the world
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.0

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Firebase Backend
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.0
  firebase_analytics: ^10.7.0
  firebase_storage: ^11.5.0
  firebase_crashlytics: ^3.4.0
  google_sign_in: ^6.2.1

  # Maps & Location
  # TODO: Uncomment in Sprint 3-4 when implementing map features
  # mapbox_gl: ^0.16.0  # Requires Mapbox SDK token configuration
  geolocator: ^11.0.0
  permission_handler: ^11.0.0
  flutter_polyline_points: ^2.0.0
  latlong2: ^0.9.0

  # HTTP & API
  dio: ^5.4.0
  # retrofit: ^4.0.0  # TODO: Add back in later sprints when needed
  json_annotation: ^4.8.0

  # UI Components
  cached_network_image: ^3.3.0
  lottie: ^3.0.0
  flutter_svg: ^2.0.0
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.7.0

  # Utilities
  intl: ^0.19.0
  uuid: ^4.0.0
  connectivity_plus: ^5.0.0
  package_info_plus: ^5.0.0
  shared_preferences: ^2.2.0

  # Monitoring
  sentry_flutter: ^7.13.0

  # Monetization (will be added in later sprints)
  # google_mobile_ads: ^5.0.0
  # purchases_flutter: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.0
  hive_generator: ^2.0.0
  riverpod_generator: ^2.3.0
  json_serializable: ^6.7.0
  # retrofit_generator: ^8.0.0  # TODO: Add back in later sprints when needed

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Assets
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
